call npm config set registry https://registry.npm.taobao.org
call npm install autoprefixer@6.6.1
call npm install babel-core@6.21.0
call npm install babel-loader@6.2.10
call npm install babel-plugin-import@1.1.0
call npm install babel-plugin-react-transform@2.0.2
call npm install babel-plugin-transform-runtime@6.23.0
call npm install babel-preset-es2015@6.18.0
call npm install babel-preset-react@6.16.0
call npm install babel-preset-stage-0@6.22.0
call npm install css-loader@0.26.1
call npm install extract-text-webpack-plugin@1.0.1
call npm install font-awesome@4.7.0
call npm install font-awesome-webpack@0.0.4
call npm install html-webpack-plugin@2.26.0
call npm install json-loader@0.5.4
call npm install less@2.7.2
call npm install less-loader@2.2.3
call npm install postcss-loader@1.2.1
call npm install react-router@3.0.0
call npm install react-transform-hmr@1.0.4
call npm install style-loader@0.13.1
call npm install url-loader@0.5.7
call npm install webpack@1.14.0
call npm install webpack-dev-server@1.16.2
call npm install antd@2.9.3
call npm install babel-polyfill@6.23.0
call npm install isomorphic-fetch@2.2.1
call npm install react@15.4.1
call npm install react-dom@15.4.1
call npm install file-loader@0.10.0
call npm install jquery.nicescroll@3.6.8
call npm install echarts@3.5.4
call npm install babili-webpack-plugin@0.1.2
call npm install draft-js@0.10.1
call npm install es6-promise@4.1.1
call npm install react-transition-group@1.2.0
call npm install reqwest
call npm install testantd
call npm install xlsx-oc@1.0.2